### ISSUE TITLE
performance issues after a certain amount of packages

### ISSUE THREAD

**Issue by AladW** [vodik/repose#42]
I have a repo that contains 322 packages, some of which are large or contain many files. Output from `repose -l`: https://paste.xinu.at/Szqf/

The issue is that adding any package takes a long time:
```
[archie@thinkpad custom]$ time repose -dvf custom.db prelink-20130503-7-x86_64.pkg.tar 
dropping prelink
writing custom.db...
writing custom.files...

real	0m0.102s
user	0m0.070s
sys	0m0.020s
[archie@thinkpad custom]$ time repose -vf custom.db prelink-20130503-7-x86_64.pkg.tar 
adding prelink 20130503-7
writing custom.db...
writing custom.files...

real	0m16.820s
user	0m0.300s
sys	0m2.220s
```
Comparison to a database which was created with `repo-add`:
```
[archie@thinkpad custom]$ time repo-remove custom.db.tar prelink
==> Extracting database to a temporary location...
==> Extracting database to a temporary location...
==> Searching for package 'prelink'...
  -> Removing existing entry 'prelink-20130503-7'...
==> Creating updated database file 'custom.db.tar'

real	0m0.198s
user	0m0.060s
sys	0m0.050s
[archie@thinkpad custom]$ time repo-add custom.db.tar prelink-20130503-7-x86_64.pkg.tar 
==> Extracting database to a temporary location...
==> Extracting database to a temporary location...
==> Adding package 'prelink-20130503-7-x86_64.pkg.tar'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'custom.db.tar'

real	0m0.273s
user	0m0.110s
sys	0m0.050s
```
I can give you more detailed statistics if you want, but a 16s difference should be reproducable.

**Comment by vodik** [comment]
Yeah, so I'm aware of this, but its never personally bothered me to the point that I really dove into it yet. Just for comparison's sake, mind trying this without a files database?

The problem is that I read the entire database into ram, than write it out again. Its a model that's worked well for the desc entries, or small packages with the files db, but it very quickly breaks down. Especially since the files are stored as a link list.

The thing is, in the past, I've tackled with alternative package structures, but they've never yielded much performance benefits.

Now `repo-add` also extracts the database in full, so there must be a way to also make this fast. Probably easiest and most likely way to do this would be to *not* parse the files database and just hold the entire file in ram. That should remove a few loops.

I'll try that now, if it works, great, if not, this will need some serious though.

**Comment by vodik** [comment]
Okay, so I don't really know where the performance regression is here. Could things to note:

1. repose scans the **entire** package pool directly and loads everything into memory, but this can be slow. Every package considered needs to be decompressed, one-by-one which is slow.
2. Even if you specifically ask to add or remove a specific package, the package pool is still consulted (so loaded) because:
  - Automatic dropping functionality always runs
  - Adding a specific package fuzzily is supported (e.g. `repose custom.db prelink` or `repose custom.db prelink-20130503-7` is supported)

Arguably auto-dropping shouldn't be happening by default, any maybe supporting the fuzzy adding is more complicated then necessary.

**However**, the package pool loading is aware of the filtering (its aware that we've passed in `prelink-20130503-7-x86_64.pkg.tar`), so it shouldn't be considering unmatched files.

I'm trying to reproduce this, but if its possible, could you provide me measurements from gperf or something?

Try compiling repose with `-pg`, run it, and share the gmon.out?

**Comment by vodik** [comment]
I'm having trouble reproducing any sort of bottleneck on add/remove

**Comment by vodik** [comment]
Mind evaluating this patch?

**Comment by AladW** [comment]
Here's the stats for 10 runs of dropping/adding a random package from my repository, using the `new-parsers` branch. Note that there's a few segfaults present (and the gdb output is optimized out even with -O0 for some reason)

https://paste.xinu.at/Ela/
contents: https://paste.xinu.at/NLW7/

**Comment by vodik** [comment]
I can't seem to reproduce any segfaults so I'll merge it in for now. Performance improvements are worth it.

**Comment by vodik** [comment]
Thanks again!

**Comment by AladW** [comment]
I've managed to get a better backtrace: https://paste.xinu.at/ROY/

If you want, I can open a separate issue for that together with an online copy of my repository.

**Comment by vodik** [comment]
Yeah, I think that's the only way I'm going to find the issue, outside of trying to write test cases against the package hash (which I think I should do anyways).
